{
<<<<<<< HEAD
	"version": 1504532342,
=======
	"version": 1502709768,
>>>>>>> 285ca1eb0511549726746db9e3a3996971bfcbf6
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
<<<<<<< HEAD
		"images/sprite-sheet0.png",
		"images/placa-sheet0.png",
		"images/iflauta-sheet0.png",
		"images/ipandeiro-sheet0.png",
		"images/ichucalho-sheet0.png",
		"images/iclarineta-sheet0.png",
		"images/ipã-sheet0.png",
		"images/bebedouro-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/fundoo-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/iviolino-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/itrompete-sheet0.png",
		"images/pandeiroi-sheet0.png",
		"images/ichocalho-sheet0.png",
		"images/iflut-sheet0.png",
		"images/iharpa-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/tchocalho-sheet0.png",
		"images/tpandeiro-sheet0.png",
		"images/tflauta-sheet0.png",
		"images/ttrompete-sheet0.png",
		"images/tviolino-sheet0.png",
		"images/tharpa-sheet0.png",
		"images/fundog-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/gameover-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/fundo-sheet0.png",
		"images/vitoria-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/bottomhome-sheet0.png",
		"images/bottomback-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/botombackp-sheet0.png",
		"images/botomhomep-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/icho-sheet0.png",
		"images/iflau-sheet0.png",
		"images/ipan-sheet0.png",
		"images/itrom-sheet0.png",
		"images/ivin-sheet0.png",
		"images/ihar-sheet0.png",
		"images/play-sheet0.png",
		"images/fundo2-sheet0.png",
		"images/ibenribau-sheet0.png",
		"images/isanfona-sheet0.png",
		"images/itambor-sheet0.png",
		"images/iviolao-sheet0.png",
		"images/violão-sheet0.png",
		"images/sanfona-sheet0.png",
		"images/benribau-sheet0.png",
		"images/tambor-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/piano-sheet0.png",
		"images/numerot2.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/icreditos-sheet0.png",
		"images/fp-sheet0.png",
		"images/historia-sheet0.png",
		"images/historia-sheet1.png",
		"images/historia-sheet2.png",
		"media/382310__myfox14__game-over-arcade.m4a",
		"media/382310__myfox14__game-over-arcade.ogg",
		"media/toquepa (online-audio-converter.com).m4a",
		"media/toquepa (online-audio-converter.com).ogg",
		"media/violao (mp3cut.net) (1).m4a",
		"media/violao (mp3cut.net) (1).ogg",
		"media/efeito sonoro - batucadatambor 1 (mp3cut.net).m4a",
		"media/efeito sonoro - batucadatambor 1 (mp3cut.net).ogg",
		"media/sanfo (mp3cut.net).m4a",
		"media/sanfo (mp3cut.net).ogg",
		"media/paranaue-capoeira (mp3cut.net).m4a",
		"media/paranaue-capoeira (mp3cut.net).ogg",
		"media/piano sound effect (mp3cut.net).m4a",
		"media/piano sound effect (mp3cut.net).ogg",
		"media/trompetes.m4a",
		"media/trompetes.ogg",
		"media/som de harpa (mp3cut.net).m4a",
		"media/som de harpa (mp3cut.net).ogg",
		"media/chocalho.m4a",
		"media/chocalho.ogg",
		"media/flauta.m4a",
		"media/flauta.ogg",
		"media/harpa.m4a",
		"media/harpa.ogg",
		"media/pandeiro.m4a",
		"media/pandeiro.ogg",
		"media/violino (mp3cut.net).m4a",
		"media/violino (mp3cut.net).ogg",
		"media/tema da vitória (piano instrumental) (mp3cut.net).m4a",
		"media/tema da vitória (piano instrumental) (mp3cut.net).ogg",
=======
		"images/iplay-sheet0.png",
		"images/sprite-sheet0.png",
		"images/placa-sheet0.png",
		"images/fundo-sheet0.png",
		"images/lamparina-sheet0.png",
		"images/iflauta-sheet0.png",
		"images/ipandeiro-sheet0.png",
		"images/estante-sheet0.png",
		"images/ibalcao-sheet0.png",
		"images/ichucalho-sheet0.png",
		"images/pc-sheet0.png",
		"images/iclarineta-sheet0.png",
		"images/iviolino-sheet0.png",
		"images/ipã-sheet0.png",
		"images/jarro-sheet0.png",
		"images/bebedouro-sheet0.png",
		"images/mfundo-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/391932_danialler_rattle (online-audio-converter.com).m4a",
		"media/391932_danialler_rattle (online-audio-converter.com).ogg",
		"media/394506__henriquebotella__notaflauta.m4a",
		"media/394506__henriquebotella__notaflauta.ogg",
		"media/382310__myfox14__game-over-arcade.m4a",
		"media/382310__myfox14__game-over-arcade.ogg",
		"media/121045_thirsk_150-clarinet-loop-2 (online-audio-converter.com).m4a",
		"media/121045_thirsk_150-clarinet-loop-2 (online-audio-converter.com).ogg",
		"media/109981_jacksonjust_loop-pandeiro-197 (online-audio-converter.com).m4a",
		"media/109981_jacksonjust_loop-pandeiro-197 (online-audio-converter.com).ogg",
		"media/toquepa (online-audio-converter.com).m4a",
		"media/toquepa (online-audio-converter.com).ogg",
		"media/56076_ldk1609_violin-tremolo-e3 (online-audio-converter.com) (1).m4a",
		"media/56076_ldk1609_violin-tremolo-e3 (online-audio-converter.com) (1).ogg",
>>>>>>> 285ca1eb0511549726746db9e3a3996971bfcbf6
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}