{
	"version": 1502709768,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/iplay-sheet0.png",
		"images/sprite-sheet0.png",
		"images/placa-sheet0.png",
		"images/fundo-sheet0.png",
		"images/lamparina-sheet0.png",
		"images/iflauta-sheet0.png",
		"images/ipandeiro-sheet0.png",
		"images/estante-sheet0.png",
		"images/ibalcao-sheet0.png",
		"images/ichucalho-sheet0.png",
		"images/pc-sheet0.png",
		"images/iclarineta-sheet0.png",
		"images/iviolino-sheet0.png",
		"images/ipã-sheet0.png",
		"images/jarro-sheet0.png",
		"images/bebedouro-sheet0.png",
		"images/mfundo-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/391932_danialler_rattle (online-audio-converter.com).m4a",
		"media/391932_danialler_rattle (online-audio-converter.com).ogg",
		"media/394506__henriquebotella__notaflauta.m4a",
		"media/394506__henriquebotella__notaflauta.ogg",
		"media/382310__myfox14__game-over-arcade.m4a",
		"media/382310__myfox14__game-over-arcade.ogg",
		"media/121045_thirsk_150-clarinet-loop-2 (online-audio-converter.com).m4a",
		"media/121045_thirsk_150-clarinet-loop-2 (online-audio-converter.com).ogg",
		"media/109981_jacksonjust_loop-pandeiro-197 (online-audio-converter.com).m4a",
		"media/109981_jacksonjust_loop-pandeiro-197 (online-audio-converter.com).ogg",
		"media/toquepa (online-audio-converter.com).m4a",
		"media/toquepa (online-audio-converter.com).ogg",
		"media/56076_ldk1609_violin-tremolo-e3 (online-audio-converter.com) (1).m4a",
		"media/56076_ldk1609_violin-tremolo-e3 (online-audio-converter.com) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}